USE GD2C2023;
GO

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'PIE_DERECHO')
BEGIN
	EXEC ('CREATE SCHEMA PIE_DERECHO')
END
GO

--drop fks
IF OBJECT_ID('PIE_DERECHO.FK_ANUNCIO_TIPO_INMUEBLE_ID', 'F') IS NOT NULL
ALTER TABLE PIE_DERECHO.BI_HECHOS_ANUNCIO
DROP CONSTRAINT FK_ANUNCIO_TIPO_INMUEBLE_ID;
GO

IF OBJECT_ID('PIE_DERECHO.FK_ANUNCIO_AMBIENTES_ID', 'F') IS NOT NULL
ALTER TABLE PIE_DERECHO.BI_HECHOS_ANUNCIO
DROP CONSTRAINT FK_ANUNCIO_AMBIENTES_ID;
GO

IF OBJECT_ID('PIE_DERECHO.FK_ANUNCIO_TIEMPO_ID', 'F') IS NOT NULL
ALTER TABLE PIE_DERECHO.BI_HECHOS_ANUNCIO
DROP CONSTRAINT FK_ANUNCIO_TIEMPO_ID;
GO

IF OBJECT_ID('PIE_DERECHO.FK_ANUNCIO_TIPO_OPERACION_ID', 'F') IS NOT NULL
ALTER TABLE PIE_DERECHO.BI_HECHOS_ANUNCIO
DROP CONSTRAINT FK_ANUNCIO_TIPO_OPERACION_ID;
GO

IF OBJECT_ID('PIE_DERECHO.FK_ANUNCIO_BARRIO_ID', 'F') IS NOT NULL
ALTER TABLE PIE_DERECHO.BI_HECHOS_ANUNCIO
DROP CONSTRAINT FK_ANUNCIO_BARRIO_ID;
GO

IF OBJECT_ID('PIE_DERECHO.FK_ANUNCIO_RANGO_METROS_ID', 'F') IS NOT NULL
ALTER TABLE PIE_DERECHO.BI_HECHOS_ANUNCIO
DROP CONSTRAINT FK_ANUNCIO_RANGO_METROS_ID;
GO

IF OBJECT_ID('PIE_DERECHO.FK_ANUNCIO_TIPO_MONEDA_ID', 'F') IS NOT NULL
ALTER TABLE PIE_DERECHO.BI_HECHOS_ANUNCIO
DROP CONSTRAINT FK_ANUNCIO_TIPO_MONEDA_ID;
GO

IF OBJECT_ID('PIE_DERECHO.FK_ANUNCIO_SUCURSAL_ID', 'F') IS NOT NULL
ALTER TABLE PIE_DERECHO.BI_HECHOS_ANUNCIO
DROP CONSTRAINT FK_ANUNCIO_SUCURSAL_ID;
GO

IF OBJECT_ID('PIE_DERECHO.FK_ANUNCIO_RANGO_ETARIO_EMPLEADO_ID', 'F') IS NOT NULL
ALTER TABLE PIE_DERECHO.BI_HECHOS_ANUNCIO
DROP CONSTRAINT FK_ANUNCIO_RANGO_ETARIO_EMPLEADO_ID;
GO

IF OBJECT_ID('PIE_DERECHO.FK_ALQUILER_RANGO_ETARIO_INQUILINO_ID', 'F') IS NOT NULL
ALTER TABLE PIE_DERECHO.BI_HECHOS_ALQUILER
DROP CONSTRAINT FK_ALQUILER_RANGO_ETARIO_INQUILINO_ID;
GO

IF OBJECT_ID('PIE_DERECHO.FK_ALQUILER_TIEMPO_ID', 'F') IS NOT NULL
ALTER TABLE PIE_DERECHO.BI_HECHOS_ALQUILER
DROP CONSTRAINT FK_ALQUILER_TIEMPO_ID;
GO

IF OBJECT_ID('PIE_DERECHO.FK_ALQUILER_BARRIO_ID', 'F') IS NOT NULL
ALTER TABLE PIE_DERECHO.BI_HECHOS_ALQUILER
DROP CONSTRAINT FK_ALQUILER_BARRIO_ID;
GO

IF OBJECT_ID('PIE_DERECHO.FK_VENTA_TIEMPO_ID', 'F') IS NOT NULL
ALTER TABLE PIE_DERECHO.BI_HECHOS_VENTA
DROP CONSTRAINT FK_VENTA_TIEMPO_ID;
GO

IF OBJECT_ID('PIE_DERECHO.FK_VENTA_TIPO_INMUEBLE_ID', 'F') IS NOT NULL
ALTER TABLE PIE_DERECHO.BI_HECHOS_VENTA
DROP CONSTRAINT FK_VENTA_TIPO_INMUEBLE_ID;
GO

IF OBJECT_ID('PIE_DERECHO.FK_VENTA_LOCALIDAD_ID', 'F') IS NOT NULL
ALTER TABLE PIE_DERECHO.BI_HECHOS_VENTA
DROP CONSTRAINT FK_VENTA_LOCALIDAD_ID;
GO

IF OBJECT_ID('PIE_DERECHO.FK_VENTA_SUCURSAL_ID', 'F') IS NOT NULL
ALTER TABLE PIE_DERECHO.BI_HECHOS_VENTA
DROP CONSTRAINT FK_VENTA_SUCURSAL_ID;
GO

--drop tables

IF OBJECT_ID ('PIE_DERECHO.BI_RANGO_ETARIO', 'U') IS NOT NULL
		DROP TABLE PIE_DERECHO.BI_RANGO_ETARIO
GO

IF OBJECT_ID('PIE_DERECHO.BI_HECHOS_ANUNCIOS', 'U') IS NOT NULL
    DROP TABLE PIE_DERECHO.BI_HECHOS_ANUNCIOS
GO

IF OBJECT_ID('PIE_DERECHO.BI_TIEMPO', 'U') IS NOT NULL
    DROP TABLE PIE_DERECHO.BI_TIEMPO
GO

IF OBJECT_ID('PIE_DERECHO.BI_TIPO_INMUEBLE', 'U') IS NOT NULL
    DROP TABLE PIE_DERECHO.BI_TIPO_INMUEBLE
GO

IF OBJECT_ID('PIE_DERECHO.BI_AMBIENTES', 'U') IS NOT NULL
    DROP TABLE PIE_DERECHO.BI_AMBIENTES
GO

IF OBJECT_ID('PIE_DERECHO.BI_RANGO_METROS', 'U') IS NOT NULL
    DROP TABLE PIE_DERECHO.BI_RANGO_METROS
GO

IF OBJECT_ID('PIE_DERECHO.BI_TIPO_OPERACION', 'U') IS NOT NULL
    DROP TABLE PIE_DERECHO.BI_TIPO_OPERACION
GO

IF OBJECT_ID('PIE_DERECHO.BI_TIPO_MONEDA', 'U') IS NOT NULL
    DROP TABLE PIE_DERECHO.BI_TIPO_MONEDA
GO

IF OBJECT_ID('PIE_DERECHO.BI_BARRIO', 'U') IS NOT NULL
	DROP TABLE PIE_DERECHO.BI_BARRIO
GO

IF OBJECT_ID('PIE_DERECHO.BI_LOCALIDAD', 'U') IS NOT NULL
    DROP TABLE PIE_DERECHO.BI_LOCALIDAD
GO

IF OBJECT_ID('PIE_DERECHO.BI_PROVINCIA', 'U') IS NOT NULL
    DROP TABLE PIE_DERECHO.BI_PROVINCIA
GO

IF OBJECT_ID('PIE_DERECHO.BI_HECHOS_ALQUILER', 'U') IS NOT NULL
	DROP TABLE PIE_DERECHO.BI_HECHOS_ALQUILER
GO

IF OBJECT_ID('PIE_DERECHO.BI_HECHOS_ANUNCIO', 'U') IS NOT NULL
	DROP TABLE PIE_DERECHO.BI_HECHOS_ANUNCIO
GO

IF OBJECT_ID('PIE_DERECHO.BI_HECHOS_VENTA', 'U') IS NOT NULL
	DROP TABLE PIE_DERECHO.BI_HECHOS_VENTA
GO

IF OBJECT_ID('PIE_DERECHO.BI_SUCURSAL', 'U') IS NOT NULL
	DROP TABLE PIE_DERECHO.BI_SUCURSAL
GO


--Drop SPs
IF OBJECT_ID('PIE_DERECHO.BI_MIGRAR_AMBIENTES', 'P') IS NOT NULL
    DROP PROCEDURE PIE_DERECHO.BI_MIGRAR_AMBIENTES
GO

IF OBJECT_ID('PIE_DERECHO.BI_MIGRAR_TIEMPO_PUBLICACION', 'P') IS NOT NULL
    DROP PROCEDURE PIE_DERECHO.BI_MIGRAR_TIEMPO_PUBLICACION
GO

IF OBJECT_ID('PIE_DERECHO.BI_MIGRAR_TIPO_MONEDA', 'P') IS NOT NULL
    DROP PROCEDURE PIE_DERECHO.BI_MIGRAR_TIPO_MONEDA
GO

IF OBJECT_ID('PIE_DERECHO.BI_MIGRAR_TIPO_OPERACION', 'P') IS NOT NULL
    DROP PROCEDURE PIE_DERECHO.BI_MIGRAR_TIPO_OPERACION
GO

IF OBJECT_ID('PIE_DERECHO.BI_MIGRAR_SUCURSAL', 'P') IS NOT NULL
    DROP PROCEDURE PIE_DERECHO.BI_MIGRAR_SUCURSAL
GO

IF OBJECT_ID('PIE_DERECHO.BI_MIGRAR_PROVINCIA', 'P') IS NOT NULL
    DROP PROCEDURE PIE_DERECHO.BI_MIGRAR_PROVINCIA
GO

IF OBJECT_ID('PIE_DERECHO.BI_MIGRAR_LOCALIDAD', 'P') IS NOT NULL
    DROP PROCEDURE PIE_DERECHO.BI_MIGRAR_LOCALIDAD
GO

IF OBJECT_ID('PIE_DERECHO.BI_MIGRAR_BARRIO', 'P') IS NOT NULL
    DROP PROCEDURE PIE_DERECHO.BI_MIGRAR_BARRIO
GO

IF OBJECT_ID('PIE_DERECHO.BI_MIGRAR_RANGO_ETARIO', 'P') IS NOT NULL
    DROP PROCEDURE PIE_DERECHO.BI_MIGRAR_RANGO_ETARIO
GO

IF OBJECT_ID('PIE_DERECHO.BI_MIGRAR_RANGO_METROS', 'P') IS NOT NULL
    DROP PROCEDURE PIE_DERECHO.BI_MIGRAR_RANGO_METROS
GO

IF OBJECT_ID('PIE_DERECHO.BI_MIGRAR_TIPO_INMUEBLE', 'P') IS NOT NULL
    DROP PROCEDURE PIE_DERECHO.BI_MIGRAR_TIPO_INMUEBLE
GO

IF OBJECT_ID('PIE_DERECHO.BI_MIGRAR_HECHOS_ANUNCIOS', 'P') IS NOT NULL
    DROP PROCEDURE PIE_DERECHO.BI_MIGRAR_HECHOS_ANUNCIOS
GO

IF OBJECT_ID('PIE_DERECHO.BI_MIGRAR_HECHOS_ALQUILER', 'P') IS NOT NULL
    DROP PROCEDURE PIE_DERECHO.BI_MIGRAR_HECHOS_ALQUILER
GO

IF OBJECT_ID('PIE_DERECHO.BI_MIGRAR_HECHOS_VENTA', 'P') IS NOT NULL
    DROP PROCEDURE PIE_DERECHO.BI_MIGRAR_HECHOS_VENTA
GO

--drop funciones
IF OBJECT_ID('PIE_DERECHO.FX_CALCULAR_RANGO_ETARIO_EMPLEADO', 'FN') IS NOT NULL
    DROP FUNCTION PIE_DERECHO.FX_CALCULAR_RANGO_ETARIO_EMPLEADO
GO

IF OBJECT_ID('PIE_DERECHO.FX_CALCULAR_RANGO_ETARIO_INQUILINO', 'FN') IS NOT NULL
    DROP FUNCTION PIE_DERECHO.FX_CALCULAR_RANGO_ETARIO_INQUILINO
GO

IF OBJECT_ID('PIE_DERECHO.FX_CALCULAR_RANGO_METROS', 'FN') IS NOT NULL
    DROP FUNCTION PIE_DERECHO.FX_CALCULAR_RANGO_METROS
GO

IF OBJECT_ID('PIE_DERECHO.FX_CALCULAR_CUATRIMESTRE', 'FN') IS NOT NULL
    DROP FUNCTION PIE_DERECHO.FX_CALCULAR_CUATRIMESTRE
GO

--drop views


--Creacion tablas DIMENSIONES 
--TODO: Verificar que los tipos de dato coincidan
--con los de la entrega anterior
CREATE TABLE PIE_DERECHO.BI_TIEMPO(
	TIEMPO_CODIGO INT IDENTITY(1, 1) PRIMARY KEY,
	TIEMPO_ANIO INT,
	TIEMPO_CUATRIMESTRE INT,
	TIEMPO_MES INT
);
GO

CREATE TABLE PIE_DERECHO.BI_RANGO_ETARIO(
	RANGO_ETARIO_CODIGO INT IDENTITY(1, 1) PRIMARY KEY,
	RANGO_ETARIO_DESCRIPCION nvarchar(50)
);
GO

CREATE TABLE PIE_DERECHO.BI_TIPO_INMUEBLE(
	TIPO_INMUEBLE_CODIGO INT PRIMARY KEY,
	TIPO_INMUEBLE nvarchar(45)
);
GO

CREATE TABLE PIE_DERECHO.BI_AMBIENTES(
	AMBIENTES_CODIGO INT PRIMARY KEY,
	AMBIENTES_CANTIDAD nvarchar(100)
);
GO

CREATE TABLE PIE_DERECHO.BI_RANGO_METROS(
	RANGO_METROS_CODIGO INT IDENTITY(1, 1) PRIMARY KEY,
	RANGO_METROS_DESCRIPCION nvarchar(50)
);
GO

CREATE TABLE PIE_DERECHO.BI_TIPO_OPERACION(
	TIPO_OPERACION_CODIGO INT PRIMARY KEY,
	TIPO_OPERACION_DESCRIPCION nvarchar(100)
);
GO

CREATE TABLE PIE_DERECHO.BI_TIPO_MONEDA(
	TIPO_MONEDA_CODIGO INT PRIMARY KEY,
	TIPO_MONEDA nvarchar(100)
);
GO

CREATE TABLE PIE_DERECHO.BI_SUCURSAL(
	SUCURSAL_CODIGO INT PRIMARY KEY,
	SUCURSAL_NOMBRE nvarchar(100)
);
GO

CREATE TABLE PIE_DERECHO.BI_BARRIO(
	BARRIO_CODIGO INT PRIMARY KEY,
	BARRIO_NOMBRE nvarchar(100)
);
GO
CREATE TABLE PIE_DERECHO.BI_LOCALIDAD(
	LOCALIDAD_CODIGO INT PRIMARY KEY,
	LOCALIDAD_NOMBRE nvarchar(100)
);
GO


CREATE TABLE PIE_DERECHO.BI_PROVINCIA(
	PROVINCIA_CODIGO INT PRIMARY KEY,
	PROVINCIA_NOMBRE nvarchar(100)
);
GO

--------------------------
--Creacion tablas hechos--
--------------------------

CREATE TABLE PIE_DERECHO.BI_HECHOS_ANUNCIO(
	id_hechos_anuncio INT IDENTITY PRIMARY KEY,
	tiempo INT NOT NULL,
	estado BIT NOT NULL,
	tipo_operacion INT NOT NULL,
	barrio INT NOT NULL,
	ambientes INT NOT NULL,
	tipo_inmueble INT NOT NULL,
	rango_metros INT NOT NULL,
	tipo_moneda INT NOT NULL,
	sucursal INT NOT NULL,
	rango_etario_empleado INT NOT NULL,
	anuncio_fecha_publicacion datetime,
	anuncio_fecha_finalizacion datetime,
	anuncio_precio_publicado numeric(18, 2)
);
GO

CREATE TABLE PIE_DERECHO.BI_HECHOS_ALQUILER(
	id_hechos_alquiler INT IDENTITY PRIMARY KEY,
	alquiler_pk INT,
	rango_etario_inquilino INT NOT NULL,
	tiempo INT NOT NULL,
	barrio INT NOT NULL,
	fecha_fin datetime,
	pago_alq_fecha datetime,
	pago_alq_fecha_vencimiento datetime,
	pago_alq_importe numeric(18, 2),
	alq_comision numeric(18, 2)
);
GO

CREATE TABLE PIE_DERECHO.BI_HECHOS_VENTA(
	id_hechos_venta INT IDENTITY PRIMARY KEY,
	tiempo INT NOT NULL,
	tipo_inmueble INT NOT NULL,
	localidad INT NOT NULL,
	sucursal INT NOT NULL,
	venta_precio numeric(18,2),
	superficie_total numeric(18, 2),
	venta_comision numeric(18, 2)
);
GO
--TODO: ver si esta bien usar el mismo esquema de la entrega ant o uno nuevo
--agregar constraints FK de las tablas de hechos a las dimensiones
ALTER TABLE PIE_DERECHO.BI_HECHOS_ANUNCIO ADD CONSTRAINT FK_ANUNCIO_TIEMPO_ID FOREIGN KEY (tiempo) REFERENCES PIE_DERECHO.BI_TIEMPO(TIEMPO_CODIGO)
GO

ALTER TABLE PIE_DERECHO.BI_HECHOS_ANUNCIO ADD CONSTRAINT FK_ANUNCIO_TIPO_OPERACION_ID FOREIGN KEY (tipo_operacion) REFERENCES PIE_DERECHO.BI_TIPO_OPERACION(TIPO_OPERACION_CODIGO)
GO

ALTER TABLE PIE_DERECHO.BI_HECHOS_ANUNCIO ADD CONSTRAINT FK_ANUNCIO_BARRIO_ID FOREIGN KEY (barrio) REFERENCES PIE_DERECHO.BI_BARRIO(BARRIO_CODIGO)
GO

ALTER TABLE PIE_DERECHO.BI_HECHOS_ANUNCIO ADD CONSTRAINT FK_ANUNCIO_AMBIENTES_ID FOREIGN KEY (ambientes) REFERENCES PIE_DERECHO.BI_AMBIENTES(AMBIENTES_CODIGO)
GO

ALTER TABLE PIE_DERECHO.BI_HECHOS_ANUNCIO ADD CONSTRAINT FK_ANUNCIO_TIPO_INMUEBLE_ID FOREIGN KEY (tipo_inmueble) REFERENCES PIE_DERECHO.BI_TIPO_INMUEBLE(TIPO_INMUEBLE_CODIGO)
GO

ALTER TABLE PIE_DERECHO.BI_HECHOS_ANUNCIO ADD CONSTRAINT FK_ANUNCIO_RANGO_METROS_ID FOREIGN KEY (rango_metros) REFERENCES PIE_DERECHO.BI_RANGO_METROS(RANGO_METROS_CODIGO)
GO

ALTER TABLE PIE_DERECHO.BI_HECHOS_ANUNCIO ADD CONSTRAINT FK_ANUNCIO_TIPO_MONEDA_ID FOREIGN KEY (tipo_moneda) REFERENCES PIE_DERECHO.BI_TIPO_MONEDA(TIPO_MONEDA_CODIGO)
GO

ALTER TABLE PIE_DERECHO.BI_HECHOS_ANUNCIO ADD CONSTRAINT FK_ANUNCIO_SUCURSAL_ID FOREIGN KEY (sucursal) REFERENCES PIE_DERECHO.BI_SUCURSAL(SUCURSAL_CODIGO)
GO

ALTER TABLE PIE_DERECHO.BI_HECHOS_ANUNCIO ADD CONSTRAINT FK_ANUNCIO_RANGO_ETARIO_EMPLEADO_ID FOREIGN KEY (rango_etario_empleado) REFERENCES PIE_DERECHO.BI_RANGO_ETARIO(RANGO_ETARIO_CODIGO)
GO

ALTER TABLE PIE_DERECHO.BI_HECHOS_ALQUILER ADD CONSTRAINT FK_ALQUILER_RANGO_ETARIO_INQUILINO_ID FOREIGN KEY (rango_etario_inquilino) REFERENCES PIE_DERECHO.BI_RANGO_ETARIO(RANGO_ETARIO_CODIGO)
GO

ALTER TABLE PIE_DERECHO.BI_HECHOS_ALQUILER ADD CONSTRAINT FK_ALQUILER_TIEMPO_ID FOREIGN KEY (tiempo) REFERENCES PIE_DERECHO.BI_TIEMPO(TIEMPO_CODIGO)
GO

ALTER TABLE PIE_DERECHO.BI_HECHOS_ALQUILER ADD CONSTRAINT FK_ALQUILER_BARRIO_ID FOREIGN KEY (barrio) REFERENCES PIE_DERECHO.BI_BARRIO(BARRIO_CODIGO)
GO

ALTER TABLE PIE_DERECHO.BI_HECHOS_VENTA ADD CONSTRAINT FK_VENTA_TIEMPO_ID FOREIGN KEY (tiempo) REFERENCES PIE_DERECHO.BI_TIEMPO(TIEMPO_CODIGO)
GO

ALTER TABLE PIE_DERECHO.BI_HECHOS_VENTA ADD CONSTRAINT FK_VENTA_TIPO_INMUEBLE_ID FOREIGN KEY (tipo_inmueble) REFERENCES PIE_DERECHO.BI_TIPO_INMUEBLE(TIPO_INMUEBLE_CODIGO)
GO

ALTER TABLE PIE_DERECHO.BI_HECHOS_VENTA ADD CONSTRAINT FK_VENTA_LOCALIDAD_ID FOREIGN KEY (localidad) REFERENCES PIE_DERECHO.BI_LOCALIDAD(LOCALIDAD_CODIGO)
GO

ALTER TABLE PIE_DERECHO.BI_HECHOS_VENTA ADD CONSTRAINT FK_VENTA_SUCURSAL_ID FOREIGN KEY (sucursal) REFERENCES PIE_DERECHO.BI_SUCURSAL(SUCURSAL_CODIGO)
GO

--funciones
CREATE FUNCTION PIE_DERECHO.FX_CALCULAR_RANGO_ETARIO_EMPLEADO(@EMPLEADO INT)
RETURNS INT
BEGIN
	DECLARE @FECHA_NACIMIENTO SMALLDATETIME
	DECLARE @EDAD INT
	DECLARE @ID_RANGO_ETARIO_EMPLEADO INT
	SET @FECHA_NACIMIENTO = (SELECT AGENTE_FECHA_NAC
							FROM PIE_DERECHO.agentes
							WHERE AGENTE_CODIGO = @EMPLEADO)
	SET @EDAD = YEAR(GETDATE()) - YEAR(@FECHA_NACIMIENTO)

	IF @EDAD < 25
		SET @ID_RANGO_ETARIO_EMPLEADO = 1
	ELSE IF @EDAD BETWEEN  25 AND 35
		SET @ID_RANGO_ETARIO_EMPLEADO = 2
	ELSE IF @EDAD BETWEEN 35 AND 50
		SET @ID_RANGO_ETARIO_EMPLEADO = 3
	ELSE IF @EDAD > 50
		SET @ID_RANGO_ETARIO_EMPLEADO = 4

RETURN @ID_RANGO_ETARIO_EMPLEADO
END
GO

CREATE FUNCTION PIE_DERECHO.FX_CALCULAR_RANGO_ETARIO_INQUILINO(@INQUILINO INT)
RETURNS INT
BEGIN
	DECLARE @FECHA_NACIMIENTO SMALLDATETIME
	DECLARE @EDAD INT
	DECLARE @ID_RANGO_ETARIO_INQUILINO INT
	SET @FECHA_NACIMIENTO = (SELECT INQUILINO_FECHA_NAC
							FROM PIE_DERECHO.inquilinos
							WHERE INQUILINO_CODIGO = @INQUILINO)
	SET @EDAD = YEAR(GETDATE()) - YEAR(@FECHA_NACIMIENTO)

	IF @EDAD < 25
		SET @ID_RANGO_ETARIO_INQUILINO = 1
	ELSE IF @EDAD BETWEEN  25 AND 35
		SET @ID_RANGO_ETARIO_INQUILINO = 2
	ELSE IF @EDAD BETWEEN 35 AND 50
		SET @ID_RANGO_ETARIO_INQUILINO = 3
	ELSE IF @EDAD > 50
		SET @ID_RANGO_ETARIO_INQUILINO = 4

RETURN @ID_RANGO_ETARIO_INQUILINO
END
GO

CREATE FUNCTION PIE_DERECHO.FX_CALCULAR_RANGO_METROS(@INMUEBLE INT)
RETURNS INT
BEGIN
	DECLARE @SUPERFICIE numeric(18, 2)
	DECLARE @ID_RANGO_METROS INT

	SET @SUPERFICIE = (SELECT i.INMUEBLE_SUPERFICIETOTAL
					   FROM PIE_DERECHO.inmuebles i
					   WHERE i.INMUEBLE_PK = @INMUEBLE)

	IF @SUPERFICIE < 35
		SET @ID_RANGO_METROS = 1
	ELSE IF @SUPERFICIE BETWEEN 35 AND 55
		SET @ID_RANGO_METROS = 2
	ELSE IF @SUPERFICIE BETWEEN 55 AND 75
		SET @ID_RANGO_METROS = 3
	ELSE IF @SUPERFICIE BETWEEN 75 AND 100
		SET @ID_RANGO_METROS = 4
	ELSE IF @SUPERFICIE > 100
		SET @ID_RANGO_METROS = 5

RETURN @ID_RANGO_METROS
END
GO

CREATE FUNCTION PIE_DERECHO.FX_CALCULAR_CUATRIMESTRE(@FECHA datetime)
RETURNS INT
BEGIN
	DECLARE @CUATRIMESTRE INT

	SET @CUATRIMESTRE =
	CASE 
		WHEN MONTH(@FECHA) BETWEEN 1 AND 4 THEN 1
		WHEN MONTH(@FECHA) BETWEEN 5 AND 8 THEN 2
		WHEN MONTH(@FECHA) BETWEEN 9 AND 12 THEN 3
		END
	RETURN @CUATRIMESTRE
END
GO
---------------------------
--Migraciones Dimensiones--
---------------------------
--Creo que habria que hacer otra para la fecha de finalizacion
CREATE PROCEDURE PIE_DERECHO.BI_MIGRAR_AMBIENTES
AS
BEGIN
INSERT INTO PIE_DERECHO.BI_AMBIENTES
SELECT DISTINCT
	AMBIENTES_CODIGO,
	AMBIENTES_CANT_INMUEBLE
FROM PIE_DERECHO.ambientes
END
GO

CREATE PROCEDURE PIE_DERECHO.BI_MIGRAR_TIEMPO_PUBLICACION
AS
BEGIN
INSERT INTO BI_TIEMPO
SELECT DISTINCT
	YEAR(a.ANUNCIO_FECHA_PUBLICACION),
	DATEPART(Q, a.ANUNCIO_FECHA_PUBLICACION),
	DATEPART(M, a.ANUNCIO_FECHA_PUBLICACION)
FROM PIE_DERECHO.anuncios a
END
GO

CREATE PROCEDURE PIE_DERECHO.BI_MIGRAR_TIPO_MONEDA
AS
BEGIN
INSERT INTO BI_TIPO_MONEDA
SELECT DISTINCT
	m.MONEDA_CODIGO,
	m.MONEDA_NOMBRE
FROM PIE_DERECHO.monedas m
END
GO

CREATE PROCEDURE PIE_DERECHO.BI_MIGRAR_TIPO_OPERACION
AS
BEGIN
INSERT INTO BI_TIPO_OPERACION
SELECT DISTINCT
	t.TIPO_OPERACION_CODIGO,
	t.TIPO_OPERACION_ANUNCIO
FROM PIE_DERECHO.tipos_de_operacion t
END
GO


CREATE PROCEDURE PIE_DERECHO.BI_MIGRAR_SUCURSAL
AS
BEGIN
INSERT INTO BI_SUCURSAL
SELECT DISTINCT
	s.SUCURSAL_PK,
	s.SUCURSAL_NOMBRE
FROM PIE_DERECHO.sucursales s
END
GO

CREATE PROCEDURE PIE_DERECHO.BI_MIGRAR_BARRIO
AS
BEGIN
INSERT INTO BI_BARRIO(BARRIO_CODIGO, BARRIO_NOMBRE)
SELECT DISTINCT
	b.BARRIO_CODIGO,
	b.BARRIO_INMUEBLE
FROM PIE_DERECHO.barrios b
END
GO

CREATE PROCEDURE PIE_DERECHO.BI_MIGRAR_PROVINCIA
AS
BEGIN
INSERT INTO BI_PROVINCIA(PROVINCIA_CODIGO, PROVINCIA_NOMBRE)
SELECT DISTINCT
	p.PROVINCIAS_CODIGO,
	p.PROVINCIA_NOMBRE
FROM PIE_DERECHO.provincias p
END
GO

CREATE PROCEDURE PIE_DERECHO.BI_MIGRAR_LOCALIDAD
AS
BEGIN
INSERT INTO BI_LOCALIDAD(LOCALIDAD_CODIGO,LOCALIDAD_NOMBRE)
SELECT DISTINCT
	l.LOCALIDAD_CODIGO,
	l.LOCALIDAD_NOMBRE
FROM PIE_DERECHO.localidades l
END
GO

CREATE PROCEDURE PIE_DERECHO.BI_MIGRAR_RANGO_ETARIO
AS
BEGIN
	INSERT INTO BI_RANGO_ETARIO(RANGO_ETARIO_DESCRIPCION)
		VALUES('<25')
	INSERT INTO BI_RANGO_ETARIO(RANGO_ETARIO_DESCRIPCION)
		VALUES('25-35')
	INSERT INTO BI_RANGO_ETARIO(RANGO_ETARIO_DESCRIPCION)
		VALUES('35-50')
	INSERT INTO BI_RANGO_ETARIO(RANGO_ETARIO_DESCRIPCION)
		VALUES('>50')
END
GO

CREATE PROCEDURE PIE_DERECHO.BI_MIGRAR_RANGO_METROS
AS
BEGIN
	INSERT INTO BI_RANGO_METROS(RANGO_METROS_DESCRIPCION)
		VALUES('<35')
	INSERT INTO BI_RANGO_METROS(RANGO_METROS_DESCRIPCION)
		VALUES('<35-55')
	INSERT INTO BI_RANGO_METROS(RANGO_METROS_DESCRIPCION)
		VALUES('55-75')
	INSERT INTO BI_RANGO_METROS(RANGO_METROS_DESCRIPCION)
		VALUES('75-100')
	INSERT INTO BI_RANGO_METROS(RANGO_METROS_DESCRIPCION)
		VALUES('>100')			
END
GO

CREATE PROCEDURE PIE_DERECHO.BI_MIGRAR_TIPO_INMUEBLE
AS
BEGIN
INSERT INTO PIE_DERECHO.BI_TIPO_INMUEBLE
SELECT DISTINCT
	ti.TIPO_INMUEBLE_CODIGO,
	ti.TIPO_INMUEBLE_INMUEBLE
FROM PIE_DERECHO.tipos_de_inmueble ti
END
GO

----------------------
--Migraciones HECHOS--
----------------------

CREATE PROCEDURE PIE_DERECHO.BI_MIGRAR_HECHOS_ANUNCIOS
AS
BEGIN
INSERT INTO PIE_DERECHO.BI_HECHOS_ANUNCIO(
	tiempo,
	estado,
	tipo_operacion,
	barrio,
	ambientes,
	tipo_inmueble,
	rango_metros,
	tipo_moneda,
	sucursal,
	rango_etario_empleado,
	anuncio_fecha_publicacion,
	anuncio_fecha_finalizacion,
	anuncio_precio_publicado
)
SELECT DISTINCT
	t.TIEMPO_CODIGO, --ID TIEMPO
	(CASE WHEN a.ANUNCIO_ESTADO = 'Finalizado' THEN 0 ELSE 1 END ),
	tiop.TIPO_OPERACION_CODIGO, --ID TIPO OPERACION
	bb.BARRIO_CODIGO , --ID BARRIO
	amb.AMBIENTES_CODIGO , --ID AMBIENTES
	bti.TIPO_INMUEBLE_CODIGO , --TIPO INMUEBLES
	rm.RANGO_METROS_CODIGO, --RANGO METROS
	tm.TIPO_MONEDA_CODIGO, --TIPO MONEDA
	bs.SUCURSAL_CODIGO , --SUCURSALES
	re.RANGO_ETARIO_CODIGO, --RANGO ETARIO EMPLEADO
	a.ANUNCIO_FECHA_PUBLICACION,
	a.ANUNCIO_FECHA_FINALIZACION,
	a.ANUNCIO_PRECIO_PUBLICADO
FROM PIE_DERECHO.anuncios a
JOIN PIE_DERECHO.inmuebles i ON i.INMUEBLE_PK = a.ANUNCIO_INMUEBLE_PK
JOIN PIE_DERECHO.BI_BARRIO bb ON bb.BARRIO_CODIGO =  i.INMUEBLE_BARRIO_CODIGO
JOIN PIE_DERECHO.BI_AMBIENTES amb ON amb.AMBIENTES_CODIGO = i.INMUEBLE_AMBIENTES_CODIGO
JOIN PIE_DERECHO.BI_TIPO_INMUEBLE bti ON bti.TIPO_INMUEBLE_CODIGO = i.INMUEBLE_TIPO_INMUEBLE_CODIGO 
JOIN PIE_DERECHO.agentes ag ON ag.AGENTE_CODIGO = a.ANUNCIO_AGENTE_CODIGO
JOIN PIE_DERECHO.BI_SUCURSAL bs ON bs.SUCURSAL_CODIGO = ag.AGENTE_SUCURSAL_PK   
JOIN PIE_DERECHO.BI_TIEMPO t ON t.TIEMPO_ANIO = DATEPART(YEAR,a.ANUNCIO_FECHA_PUBLICACION) AND t.TIEMPO_MES = DATEPART(MONTH, a.ANUNCIO_FECHA_PUBLICACION) AND t.TIEMPO_CUATRIMESTRE = PIE_DERECHO.FX_CALCULAR_CUATRIMESTRE(a.ANUNCIO_FECHA_PUBLICACION)
JOIN PIE_DERECHO.BI_TIPO_OPERACION tiop ON tiop.TIPO_OPERACION_CODIGO = a.ANUNCIO_TIPO_OPERACION_CODIGO
JOIN PIE_DERECHO.BI_RANGO_ETARIO re ON re.RANGO_ETARIO_CODIGO = PIE_DERECHO.FX_CALCULAR_RANGO_ETARIO_EMPLEADO(a.ANUNCIO_AGENTE_CODIGO)
JOIN PIE_DERECHO.BI_RANGO_METROS rm ON rm.RANGO_METROS_CODIGO = PIE_DERECHO.FX_CALCULAR_RANGO_METROS(a.ANUNCIO_INMUEBLE_PK)
JOIN PIE_DERECHO.BI_TIPO_MONEDA tm ON tm.TIPO_MONEDA_CODIGO = a.ANUNCIO_MONEDA_CODIGO
END
GO


CREATE PROCEDURE PIE_DERECHO.BI_MIGRAR_HECHOS_ALQUILER
AS
BEGIN
INSERT INTO PIE_DERECHO.BI_HECHOS_ALQUILER(
	alquiler_pk,
	rango_etario_inquilino,
	tiempo,
	barrio,
	fecha_fin,
	pago_alq_fecha,
	pago_alq_fecha_vencimiento,
	pago_alq_importe,
	alq_comision
)
SELECT DISTINCT
	a.ALQUILER_PK, --alquiler PK
	re.RANGO_ETARIO_CODIGO, --RANGO ETARIO INQUILINO	
	t.TIEMPO_CODIGO, --TIEMPO
	b.BARRIO_CODIGO, --BARRIO
	a.ALQUILER_FECHA_FIN, --FECHA FIN 
	ppa.PAGO_ALQUILER_FECHA, --PAGO ALQ FECHA
	ppa.PAGO_ALQUILER_FECHA_VENCIMIENTO, --PAGO ALQ FECHA VENC
	ppa.PAGO_ALQUILER_IMPORTE,-- PAGO ALQ IMPORTE
	a.ALQUILER_COMISION --ALQ COMISION
FROM PIE_DERECHO.alquileres a
JOIN PIE_DERECHO.anuncios anun ON anun.ANUNCIO_PK = a.ALQUILER_VENTA_ANUNCIO_PK
JOIN PIE_DERECHO.inmuebles inmu ON inmu.INMUEBLE_PK = anun.ANUNCIO_INMUEBLE_PK 
JOIN PIE_DERECHO.pagos_por_alquiler ppa ON ppa.PAGO_INQUILINO_CODIGO = a.ALQUILER_INQUILINO_CODIGO
JOIN PIE_DERECHO.BI_RANGO_ETARIO re ON re.RANGO_ETARIO_CODIGO = PIE_DERECHO.FX_CALCULAR_RANGO_ETARIO_INQUILINO(a.ALQUILER_INQUILINO_CODIGO)
JOIN PIE_DERECHO.BI_TIEMPO t ON t.TIEMPO_ANIO = DATEPART(YEAR, a.ALQUILER_FECHA_INICIO) AND t.TIEMPO_MES = DATEPART(MONTH, a.ALQUILER_FECHA_INICIO) AND t.TIEMPO_CUATRIMESTRE = PIE_DERECHO.FX_CALCULAR_CUATRIMESTRE(a.ALQUILER_FECHA_INICIO)
JOIN PIE_DERECHO.BI_BARRIO b ON b.BARRIO_CODIGO = inmu.INMUEBLE_BARRIO_CODIGO
END
GO

CREATE PROCEDURE PIE_DERECHO.BI_MIGRAR_HECHOS_VENTA
AS
BEGIN
INSERT INTO PIE_DERECHO.BI_HECHOS_VENTA(
	tiempo,
	tipo_inmueble,
	localidad,
	sucursal,
	venta_precio,
	superficie_total,
	venta_comision
)
SELECT DISTINCT
	t.TIEMPO_CODIGO, --VENTA TIEMPO	
	ti.TIPO_INMUEBLE_CODIGO, --TIPO INMUEBLE
	l.LOCALIDAD_CODIGO, --LOCALIDAD
	s.SUCURSAL_CODIGO, --SUCURSAL
	v.VENTA_PRECIO_VENTA, --VENTA PRECIO
	i.INMUEBLE_SUPERFICIETOTAL, --SUPERFICIE TOTAL
	v.VENTA_COMISION --COMISION
FROM PIE_DERECHO.ventas v
JOIN PIE_DERECHO.anuncios a ON a.ANUNCIO_PK = v.VENTA_ANUNCIO_PK 
JOIN PIE_DERECHO.agentes agen ON agen.AGENTE_CODIGO = a.ANUNCIO_AGENTE_CODIGO
JOIN PIE_DERECHO.inmuebles i ON i.INMUEBLE_PK = a.ANUNCIO_INMUEBLE_PK
JOIN PIE_DERECHO.BI_TIPO_INMUEBLE ti ON ti.TIPO_INMUEBLE_CODIGO = i.INMUEBLE_TIPO_INMUEBLE_CODIGO 
JOIN PIE_DERECHO.barrios b ON b.BARRIO_CODIGO = i.INMUEBLE_BARRIO_CODIGO
JOIN PIE_DERECHO.BI_LOCALIDAD l ON l.LOCALIDAD_CODIGO = b.BARRIO_LOCALIDAD_CODIGO  
JOIN PIE_DERECHO.BI_TIEMPO t ON t.TIEMPO_ANIO = DATEPART(YEAR,v.VENTA_FECHA) AND t.TIEMPO_CUATRIMESTRE = PIE_DERECHO.FX_CALCULAR_CUATRIMESTRE(v.VENTA_FECHA) AND t.TIEMPO_MES = DATEPART(MONTH,v.VENTA_FECHA)
JOIN PIE_DERECHO.BI_SUCURSAL s ON s.SUCURSAL_CODIGO = agen.AGENTE_SUCURSAL_PK
END
GO

EXEC PIE_DERECHO.BI_MIGRAR_AMBIENTES
EXEC PIE_DERECHO.BI_MIGRAR_TIEMPO_PUBLICACION
EXEC PIE_DERECHO.BI_MIGRAR_TIPO_MONEDA
EXEC PIE_DERECHO.BI_MIGRAR_TIPO_OPERACION
EXEC PIE_DERECHO.BI_MIGRAR_SUCURSAL
EXEC PIE_DERECHO.BI_MIGRAR_BARRIO
EXEC PIE_DERECHO.BI_MIGRAR_LOCALIDAD
EXEC PIE_DERECHO.BI_MIGRAR_PROVINCIA
EXEC PIE_DERECHO.BI_MIGRAR_RANGO_ETARIO
EXEC PIE_DERECHO.BI_MIGRAR_RANGO_METROS
EXEC PIE_DERECHO.BI_MIGRAR_TIPO_INMUEBLE
EXEC PIE_DERECHO.BI_MIGRAR_HECHOS_ANUNCIOS
EXEC PIE_DERECHO.BI_MIGRAR_HECHOS_ALQUILER
EXEC PIE_DERECHO.BI_MIGRAR_HECHOS_VENTA
GO

--VISTAS --> --TODO: juntar los drops arriba, despues de los drops de las funciones
--1
IF OBJECT_ID('PIE_DERECHO.VISTA_DURACION_PROMEDIO_ANUNCIOS', 'V') IS NOT NULL
    DROP VIEW PIE_DERECHO.VISTA_DURACION_PROMEDIO_ANUNCIOS;
GO

--2
IF OBJECT_ID('PIE_DERECHO.VISTA_PRECIO_PROMEDIO_ANUNCIOS', 'V') IS NOT NULL
    DROP VIEW PIE_DERECHO.VISTA_PRECIO_PROMEDIO_ANUNCIOS;
GO

--3
IF OBJECT_ID('PIE_DERECHO.VISTA_CINCO_BARRIOS', 'V') IS NOT NULL
    DROP VIEW PIE_DERECHO.VISTA_CINCO_BARRIOS;
GO

--4
IF OBJECT_ID('PIE_DERECHO.VISTA_PORCENTAJE_INCUMPLIMIENTO_PAGOS', 'V') IS NOT NULL
    DROP VIEW PIE_DERECHO.VISTA_PORCENTAJE_INCUMPLIMIENTO_PAGOS;
GO

--5
IF OBJECT_ID('PIE_DERECHO.VISTA_PORCENTAJE_PROMEDIO_INCREMENTOS_ALQUILERES', 'V') IS NOT NULL
    DROP VIEW PIE_DERECHO.VISTA_PORCENTAJE_PROMEDIO_INCREMENTOS_ALQUILERES
GO

--6
IF OBJECT_ID('PIE_DERECHO.VISTA_PRECIO_PROMEDIO_METROS_VENTA', 'V') IS NOT NULL
    DROP VIEW PIE_DERECHO.VISTA_PRECIO_PROMEDIO_METROS_VENTA;
GO

--7
IF OBJECT_ID('PIE_DERECHO.VISTA_VALOR_PROMEDIO_COMISION', 'V') IS NOT NULL
    DROP VIEW PIE_DERECHO.VISTA_VALOR_PROMEDIO_COMISION;
GO

--8
IF OBJECT_ID('PIE_DERECHO.VISTA_PORCENTAJE_OPERACIONES_CONCRETADAS', 'V') IS NOT NULL
    DROP VIEW PIE_DERECHO.VISTA_PORCENTAJE_OPERACIONES_CONCRETADAS;
GO

--9
IF OBJECT_ID('PIE_DERECHO.VISTA_MONTO_TOTAL_CIERRE_CONTRATOS', 'V') IS NOT NULL
    DROP VIEW PIE_DERECHO.VISTA_MONTO_TOTAL_CIERRE_CONTRATOS;
GO

--1
CREATE VIEW PIE_DERECHO.VISTA_DURACION_PROMEDIO_ANUNCIOS
AS
	SELECT
		AVG(DATEDIFF(DAY, a.anuncio_fecha_publicacion, a.anuncio_fecha_finalizacion)) AS 'promedio dias',
		tiop.TIPO_OPERACION_DESCRIPCION,
		b.BARRIO_NOMBRE,
		amb.AMBIENTES_CANTIDAD,
		t.TIEMPO_ANIO AS 'AÑO',
		t.TIEMPO_CUATRIMESTRE AS 'Cuatrimestre' -->revisar si tiempo contiene la data de la fecha de publicacion
	FROM PIE_DERECHO.BI_HECHOS_ANUNCIO a
	JOIN PIE_DERECHO.BI_TIPO_OPERACION tiop ON tiop.TIPO_OPERACION_CODIGO = a.tipo_operacion
	JOIN PIE_DERECHO.BI_BARRIO b ON b.BARRIO_CODIGO = a.barrio
	JOIN PIE_DERECHO.BI_AMBIENTES amb ON amb.AMBIENTES_CODIGO = a.ambientes
	JOIN PIE_DERECHO.BI_TIEMPO t ON t.TIEMPO_CODIGO = a.tiempo
	GROUP BY t.TIEMPO_ANIO, t.TIEMPO_CUATRIMESTRE, tiop.TIPO_OPERACION_DESCRIPCION, b.BARRIO_NOMBRE, amb.AMBIENTES_CANTIDAD
GO


--2
CREATE VIEW PIE_DERECHO.VISTA_PRECIO_PROMEDIO_ANUNCIOS
AS
	SELECT
		AVG(a.anuncio_precio_publicado) AS 'Promedio precio',
		tm.TIPO_MONEDA,
		tiop.TIPO_OPERACION_DESCRIPCION,
		ti.TIPO_INMUEBLE,
		rm.RANGO_METROS_DESCRIPCION,
		t.TIEMPO_ANIO,
		t.TIEMPO_CUATRIMESTRE
	FROM PIE_DERECHO.BI_HECHOS_ANUNCIO a
	JOIN PIE_DERECHO.BI_TIPO_OPERACION tiop ON tiop.TIPO_OPERACION_CODIGO = a.tipo_operacion
	JOIN PIE_DERECHO.BI_TIPO_INMUEBLE ti ON ti.TIPO_INMUEBLE_CODIGO = a.tipo_inmueble
	JOIN PIE_DERECHO.BI_RANGO_METROS rm ON rm.RANGO_METROS_CODIGO = a.rango_metros
	JOIN PIE_DERECHO.BI_TIEMPO t ON t.TIEMPO_CODIGO = a.tiempo
	JOIN PIE_DERECHO.BI_TIPO_MONEDA tm ON tm.TIPO_MONEDA_CODIGO = a.tipo_moneda
	GROUP BY t.TIEMPO_ANIO, t.TIEMPO_CUATRIMESTRE, tiop.TIPO_OPERACION_DESCRIPCION, ti.TIPO_INMUEBLE, rm.RANGO_METROS_DESCRIPCION, tm.TIPO_MONEDA
GO


--3
CREATE VIEW PIE_DERECHO.VISTA_CINCO_BARRIOS
AS
	SELECT * FROM (
		SELECT
		t.TIEMPO_ANIO,
		t.TIEMPO_CUATRIMESTRE,
		re.RANGO_ETARIO_DESCRIPCION,
		b.BARRIO_NOMBRE,
		COUNT(*) AS 'Cant. Alquileres',
		ROW_NUMBER() OVER (PARTITION BY t.TIEMPO_ANIO, t.TIEMPO_CUATRIMESTRE, re.RANGO_ETARIO_DESCRIPCION ORDER BY COUNT(*) DESC) AS 'Posicion'
	FROM PIE_DERECHO.BI_HECHOS_ALQUILER a
	JOIN PIE_DERECHO.BI_BARRIO b ON b.BARRIO_CODIGO = a.barrio
	JOIN PIE_DERECHO.BI_RANGO_ETARIO re ON re.RANGO_ETARIO_CODIGO = a.rango_etario_inquilino
	JOIN PIE_DERECHO.BI_TIEMPO t ON t.TIEMPO_CODIGO = a.tiempo
	GROUP BY t.TIEMPO_ANIO, t.TIEMPO_CUATRIMESTRE, re.RANGO_ETARIO_DESCRIPCION, b.BARRIO_NOMBRE
) AS SubQuery
WHERE Posicion <= 5
GO

--4
CREATE VIEW PIE_DERECHO.VISTA_PORCENTAJE_INCUMPLIMIENTO_PAGOS
AS
    SELECT
        t.TIEMPO_ANIO,
        t.TIEMPO_MES,
        COUNT(*) AS 'TotalPagos',
        SUM(CASE WHEN a.pago_alq_fecha > a.pago_alq_fecha_vencimiento THEN 1 ELSE 0 END) AS 'Incumplimientos',
        (SUM(CASE WHEN a.pago_alq_fecha > a.pago_alq_fecha_vencimiento THEN 1.0 ELSE 0 END) / COUNT(*)) * 100 AS 'PorcentajeIncumplimiento'
    FROM PIE_DERECHO.BI_HECHOS_ALQUILER a
    JOIN PIE_DERECHO.BI_TIEMPO t ON t.TIEMPO_CODIGO = a.tiempo
    GROUP BY t.TIEMPO_ANIO, t.TIEMPO_MES
GO
 
--5
CREATE VIEW PIE_DERECHO.VISTA_PORCENTAJE_PROMEDIO_INCREMENTOS_ALQUILERES
AS
	 SELECT
        t.TIEMPO_ANIO,
        t.TIEMPO_MES,
        AVG(CASE
                WHEN PrevPagoAlqImporte IS NOT NULL 
                THEN ((ha.pago_alq_importe - PrevPagoAlqImporte) / PrevPagoAlqImporte) * 100
                ELSE 0 
            END) AS Porcentaje_Promedio_Incremento
    FROM
        PIE_DERECHO.BI_HECHOS_ALQUILER ha
    INNER JOIN
        PIE_DERECHO.BI_TIEMPO t ON ha.tiempo = t.TIEMPO_CODIGO
    OUTER APPLY (
        SELECT TOP 1 pago_alq_importe AS PrevPagoAlqImporte
        FROM PIE_DERECHO.BI_HECHOS_ALQUILER ha_inner
        WHERE ha_inner.alquiler_pk = ha.alquiler_pk
            AND ha_inner.tiempo < ha.tiempo
        ORDER BY ha_inner.tiempo DESC
    ) AS PrevPagoAlq
    GROUP BY
        t.TIEMPO_ANIO,
        t.TIEMPO_MES;
GO

--6
CREATE VIEW PIE_DERECHO.VISTA_PRECIO_PROMEDIO_METROS_VENTA
AS
	SELECT DISTINCT
		AVG(v.venta_precio/v.superficie_total) AS 'Precio promedio venta m2',
		t.TIEMPO_ANIO,
		t.TIEMPO_CUATRIMESTRE,
		ti.TIPO_INMUEBLE,
		l.LOCALIDAD_NOMBRE
	FROM PIE_DERECHO.BI_HECHOS_VENTA v
	JOIN PIE_DERECHO.BI_TIPO_INMUEBLE ti ON ti.TIPO_INMUEBLE_CODIGO = v.tipo_inmueble
	JOIN PIE_DERECHO.BI_LOCALIDAD l ON l.LOCALIDAD_CODIGO = v.localidad
	JOIN PIE_DERECHO.BI_TIEMPO t ON t.TIEMPO_CODIGO = v.tiempo
	GROUP BY t.TIEMPO_ANIO, t.TIEMPO_CUATRIMESTRE, l.LOCALIDAD_NOMBRE, ti.TIPO_INMUEBLE
GO

--7

CREATE VIEW PIE_DERECHO.VISTA_VALOR_PROMEDIO_COMISION
AS

	SELECT 
		bto.TIPO_OPERACION_DESCRIPCION,
		s.SUCURSAL_NOMBRE,
		t.TIEMPO_CUATRIMESTRE,
		t.TIEMPO_ANIO,
		(CASE
                WHEN bto.TIPO_OPERACION_DESCRIPCION = 'Tipo Operación Venta' 
                THEN ( SELECT avg(v1.venta_comision) FROM PIE_DERECHO.BI_HECHOS_VENTA v1
						JOIN PIE_DERECHO.BI_TIEMPO tv ON tv.TIEMPO_CODIGO = v1.tiempo
						WHERE tv.TIEMPO_CUATRIMESTRE = t.TIEMPO_CUATRIMESTRE 
						AND tv.TIEMPO_ANIO = t.TIEMPO_ANIO)
                ELSE ( SELECT avg(a1.alq_comision) FROM PIE_DERECHO.BI_HECHOS_ALQUILER a1
						JOIN PIE_DERECHO.BI_TIEMPO tv ON tv.TIEMPO_CODIGO = a1.tiempo
						WHERE tv.TIEMPO_CUATRIMESTRE = t.TIEMPO_CUATRIMESTRE 
						AND tv.TIEMPO_ANIO = t.TIEMPO_ANIO)
        END) AS Porcentaje_Promedio_Incremento

	FROM PIE_DERECHO.BI_HECHOS_ANUNCIO a
	JOIN PIE_DERECHO.BI_TIPO_OPERACION bto ON bto.TIPO_OPERACION_CODIGO = a.tipo_operacion
	JOIN PIE_DERECHO.BI_TIEMPO t ON t.TIEMPO_CODIGO = a.tiempo  
	JOIN PIE_DERECHO.BI_SUCURSAL s ON s.SUCURSAL_CODIGO = a.sucursal
	GROUP BY bto.TIPO_OPERACION_DESCRIPCION, t.TIEMPO_CUATRIMESTRE,t.TIEMPO_ANIO, s.SUCURSAL_NOMBRE

GO

--8
CREATE VIEW PIE_DERECHO.VISTA_PORCENTAJE_OPERACIONES_CONCRETADAS
AS
	SELECT
		s.SUCURSAL_NOMBRE,
		t.TIEMPO_ANIO,
		e.RANGO_ETARIO_DESCRIPCION,
		SUM(CASE
            WHEN a.estado = 1 THEN 1
            ELSE 0
        END) *100 /COUNT(*) 'porcentaje'
	FROM PIE_DERECHO.BI_HECHOS_ANUNCIO a
	JOIN PIE_DERECHO.BI_SUCURSAL s ON s.SUCURSAL_CODIGO = a.sucursal 
	JOIN PIE_DERECHO.BI_TIEMPO t ON t.TIEMPO_CODIGO = a.tiempo
	JOIN PIE_DERECHO.BI_RANGO_ETARIO e ON e.RANGO_ETARIO_CODIGO = a.rango_etario_empleado 
	GROUP BY s.SUCURSAL_NOMBRE,t.TIEMPO_ANIO,e.RANGO_ETARIO_DESCRIPCION;
GO

--9
CREATE VIEW PIE_DERECHO.VISTA_MONTO_TOTAL_CIERRE_CONTRATOS
AS
	SELECT DISTINCT
		a.tipo_operacion,
		t.TIEMPO_CUATRIMESTRE,
		a.sucursal,
		(CASE
            WHEN a.tipo_operacion = 3 
			THEN (SELECT SUM(v.venta_comision + v.venta_precio) 
					FROM PIE_DERECHO.BI_HECHOS_VENTA v 
					WHERE t.TIEMPO_CODIGO = v.tiempo AND a.sucursal = v.sucursal)
            ELSE (SELECT SUM(alq.pago_alq_importe + alq.alq_comision) 
					FROM PIE_DERECHO.BI_HECHOS_ALQUILER alq 
					WHERE t.TIEMPO_CODIGO = alq.tiempo)
        END) 'monto total'
	FROM PIE_DERECHO.BI_HECHOS_ANUNCIO a	
	JOIN PIE_DERECHO.BI_TIEMPO t ON t.TIEMPO_CODIGO = a.tiempo

GO




